server:
  port: 7978

spring:
  application:
    name: PAYMENT-SERVICE   # must match Gateway route
  boot:
    admin:
      client:
        url: http://localhost:1111/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
management:
  endpoints:
    web:
      exposure:
        include: '*'

# application.yml (Appointment Microservice)

resilience4j:
  circuitbreaker:
    instances:
      # Circuit Breaker specifically for the Feign client
      welcomeOrderServiceCircuit: 
        failureRateThreshold: 50
        waitDurationInOpenState: 1000s
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
  # retry:
  #   instances:
  #     welcomeOrderServiceRetry:
  #       maxAttempts: 3
  #       waitDuration: 200ms
  #       retryExceptions:
  #         - java.util.concurrent.TimeoutException
  #         - java.io.IOException
  #         - org.springframework.web.client.ResourceAccessException